name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    uses: emitra-labs/actions/.github/workflows/build-svelte.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit

  deploy:
    uses: emitra-labs/actions/.github/workflows/deploy-docker.yaml@main
    needs: build
    permissions:
      contents: read
    with:
      group: webs
    secrets: inherit
